const priceTable = {
    "Pe&Mao": "60",
    "Escova I": "40",
    "Escova II": "45",
    "Escova III": "50",
    "Escova IV": "55",
    "Escova V": "60",
    "Escova VI": "65",
    "Escova VII": "70",
    "Pe": "30",
    "Mao": "20",
    "Hidratacao I": "90",
    "Hidratacao II": "120",
    "Nutricao": "100",
    "Reconstrucao": "100",
    "Sobrancelha": "20",
    "Corte": "100",
    "Aplicacao Tinta": "40",
    "Coloracao I": "120",
    "Coloracao II": "200",
    "Mechas I": "250",
    "Mechas II": "350",
    "Buco": "20"    
}